//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyHigh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Airport
    {
        public Airport()
        {
            this.FromFlights = new HashSet<Flight>();
            this.ToFlights = new HashSet<Flight>();
        }
    
        public int AirportId { get; set; }

        [DisplayName("Airport Code")]
        public string AirportCode { get; set; }
        public string AirportName { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Flight> FromFlights { get; set; }
        public virtual ICollection<Flight> ToFlights { get; set; }
    }
}
