//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyHigh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Tickets = new HashSet<Ticket>();
        }

        [DisplayName("Booking Id")]
        public long BookingId { get; set; }

        [DisplayName("First Name")]
        public string BookingFirstName { get; set; }
        [DisplayName("Last Name")]
        public string BookingLastName { get; set; }
        [DisplayName("ID Type")]
        public string BookingIdType { get; set; }
        [DisplayName("ID Number")]
        public string BookingIdNumber { get; set; }
        [DisplayName("Timestamp")]
        public System.DateTime BookingTimestamp { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
