//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyHigh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public long BookingId { get; set; }
        public string BookingFirstName { get; set; }
        public string BookingLastName { get; set; }
        public string BookingIdType { get; set; }
        public string BookingIdNumber { get; set; }
        public System.DateTime BookingTimestamp { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
