//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyHigh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErlanggaEntities : DbContext
    {
        public ErlanggaEntities()
            : base("name=ErlanggaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Airport> Airports { get; set; }
        public DbSet<Baggage> Baggages { get; set; }
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<Flight> Flights { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Pilot> Pilots { get; set; }
        public DbSet<PilotSchedule> PilotSchedules { get; set; }
        public DbSet<Plane> Planes { get; set; }
        public DbSet<PlaneClass> PlaneClasses { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Steward> Stewards { get; set; }
        public DbSet<StewardSchedule> StewardSchedules { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TicketInstance> TicketInstances { get; set; }
    }
}
