//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyHigh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public Pilot()
        {
            this.PilotSchedules = new HashSet<PilotSchedule>();
        }
    
        public int PilotId { get; set; }
        public string PilotName { get; set; }
    
        public virtual ICollection<PilotSchedule> PilotSchedules { get; set; }
    }
}
