//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyHigh.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Plane
    {
        public Plane()
        {
            this.PlaneClasses = new HashSet<PlaneClass>();
            this.Schedules = new HashSet<Schedule>();
        }

        public int PlaneId { get; set; }
        public string PlaneType { get; set; }
        public double MaximumWeight { get; set; }

        public string PlaneInfoDisplay
        {
            get
            {
                return PlaneId + " - " + PlaneType;
            }
        }

        public virtual ICollection<PlaneClass> PlaneClasses { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
