//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyHigh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Steward
    {
        public Steward()
        {
            this.StewardSchedules = new HashSet<StewardSchedule>();
        }
    
        public int StewardId { get; set; }
        public string StewardName { get; set; }
    
        public virtual ICollection<StewardSchedule> StewardSchedules { get; set; }
    }
}
